/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */

import java.lang.*;
import java.util.*;
import java.awt.*;
import java.lang.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    int cap;
    int rows,cols;
    String showid,screenid;
    String username;
    String bid;
   
    
    public Booking() {
        initComponents();
       
    }
    
    public Booking(int max,String show,String user,String screen){
        initComponents();
        cap = max;
        showid = show;
        username = user;
        screenid=screen;
        rows = (int)Math.sqrt(new Double(cap));
        cols=rows;
        setTitle("BOOKING");
        
        String theAlphaNumericS;
        StringBuilder builder;
        
        theAlphaNumericS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                    + "0123456789"; 

        //create the StringBuffer
        builder = new StringBuilder(5); 

        for (int m = 0; m < 5; m++) { 

            // generate numeric
            int myindex 
                = (int)(theAlphaNumericS.length() 
                        * Math.random()); 

            // add the characters
            builder.append(theAlphaNumericS 
                        .charAt(myindex)); 
        } 
        bid=builder.toString();
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
     
    dtm.setRowCount(rows);
    dtm.setColumnCount(cols);
    
     jTable1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    jTable1.setColumnSelectionAllowed(true);
    jTable1.setRowSelectionAllowed(true);
    int rowSelected = jTable1.getRowCount();
    int colSelected = jTable1.getColumnCount();
    jTable1.setSelectionBackground(Color.GRAY);
    boolean toggle = false;
    boolean extend = false;
    jTable1.changeSelection(rowSelected, colSelected, toggle, extend);
   
    
    DefaultTableModel dtm1 = (DefaultTableModel) jTable5.getModel();
    
    dtm1.setRowCount(rows);
    dtm1.setColumnCount(cols);
    
    jTable5.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    jTable5.setColumnSelectionAllowed(true);
    jTable5.setRowSelectionAllowed(true);

    jTable5.setSelectionBackground(Color.GRAY);
   
    jTable5.changeSelection(rowSelected, colSelected, toggle, extend);
    
    DefaultTableModel dtm2 = (DefaultTableModel) jTable6.getModel();
   
    dtm2.setRowCount(rows);
    dtm2.setColumnCount(cols);
    
    jTable6.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    jTable6.setColumnSelectionAllowed(true);
    jTable6.setRowSelectionAllowed(true);

  
    jTable6.setSelectionBackground(Color.GRAY);
   
    jTable6.changeSelection(rowSelected, colSelected, toggle, extend);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FRONT ROW");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(81, 176, 110, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("MIDDLE ROW");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(81, 426, 122, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("LAST ROW");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(81, 681, 95, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(317, 80, 452, 228);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(317, 326, 452, 235);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable6MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable6);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(317, 591, 452, 240);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(476, 859, 105, 37);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\Saved Pictures\\IMG.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(790, -180, 1140, 1040);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClicked
        // TODO add your handling code here:
        int rowSelected = jTable1.getRowCount();
        int colSelected = jTable1.getColumnCount();
    
    
    for(int i=0;i<rowSelected;i++){
        for(int j=0;j<colSelected;j++){
            if(jTable1.isCellSelected(i,j))
            {
                String seatno;
             //   bid=String.valueOf("B"+""+Homepage.bno);
                seatno=String.valueOf((i+1)+""+(char)('A'+j));
              int flag=0;
                try{
                     Class.forName("com.mysql.jdbc.Driver");  
                    Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
                    String query = "select * from seats where showid=?";
                    PreparedStatement prepStmt = connect.prepareStatement(query);      
                    prepStmt.setString(1,showid);
                   
                    ResultSet rs = prepStmt.executeQuery();
                    
                    while(rs.next()){
                        if(rs.getString(1).equals(seatno)){
                             JFrame f = new JFrame();
                             JOptionPane.showMessageDialog(f,seatno+" Seat is unavailable! Already Booked");
                             f.setVisible(true);
                             flag=1;
                             break;
                        }
                    }
                    connect.close();
                }
                
                catch(Exception e){}
             
                if(flag==0){
                try{
                Class.forName("com.mysql.jdbc.Driver");  
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
            
                PreparedStatement stmt=con.prepareStatement("insert into seats values(?,?,?,?,?)");  
                stmt.setString(1,seatno);
                stmt.setString(2,bid);
                stmt.setString(3,showid);
                stmt.setString(4,"Booked");
                stmt.setString(5,"FrontRow");
                
                int i3=stmt.executeUpdate();
            
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f,seatno+" Seat booked Successfully");
                f.setVisible(true);
            
                con.close();
       
        }
        
        catch(Exception e){
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f,"Insertion failed");
                f.setVisible(true);
        }
            
                }
            
            }
        }
    }

    }//GEN-LAST:event_MouseClicked

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
         int rowSelected = jTable1.getRowCount();
        int colSelected = jTable1.getColumnCount();
       int k = rowSelected;
        for(int i=0;i<rowSelected;i++){
            
        for(int j=0;j<colSelected;j++){
            
            if(jTable5.isCellSelected(i,j)){
                String seatno;
              //   bid=String.valueOf("B"+""+Homepage.bno);
                seatno=String.valueOf((k+1)+""+(char)('A'+j));
              int flag=0;
                try{
                     Class.forName("com.mysql.jdbc.Driver");  
                    Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
                    String query = "select * from seats where showid=?";
                    PreparedStatement prepStmt = connect.prepareStatement(query);      
                    prepStmt.setString(1,showid);
                   
                    ResultSet rs = prepStmt.executeQuery();
                    
                    while(rs.next()){
                        if(rs.getString(1).equals(seatno)){
                             JFrame f = new JFrame();
                             JOptionPane.showMessageDialog(f,seatno+" Seat is unavailable! Already Booked");
                             f.setVisible(true);
                             flag=1;
                             break;
                        }
                    }
                    connect.close();
                }
                
                catch(Exception e){}
             
                if(flag==0){
                try{
                Class.forName("com.mysql.jdbc.Driver");  
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
            
                PreparedStatement stmt=con.prepareStatement("insert into seats values(?,?,?,?,?)");  
                stmt.setString(1,seatno);
                stmt.setString(2,bid);
                stmt.setString(3,showid);
                stmt.setString(4,"Booked");
                stmt.setString(5,"MiddleRow");
                
                int i1=stmt.executeUpdate();
            
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f,seatno+" Seat booked Successfully");
                f.setVisible(true);
            
                con.close();
       
        }
        
        catch(Exception e){
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f,"Insertion failed");
                f.setVisible(true);
        }
                } 
            
            }
          
            
        }
        k++;
    }
    }//GEN-LAST:event_jTable5MouseClicked

    private void jTable6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable6MouseClicked
        // TODO add your handling code here:
           int rowSelected = jTable1.getRowCount();
        int colSelected = jTable1.getColumnCount();
        int k = rowSelected*2;
        for(int i=0;i<rowSelected;i++){
        for(int j=0;j<colSelected;j++){
            if(jTable6.isCellSelected(i,j))
            {
                String seatno;
               //  bid=String.valueOf("B"+""+Homepage.bno);
                seatno=String.valueOf((k+1)+""+(char)('A'+j));
                int flag=0;
                try{
                     Class.forName("com.mysql.jdbc.Driver");  
                    Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
                    String query = "select * from seats where showid=?";
                    PreparedStatement prepStmt = connect.prepareStatement(query);      
                    prepStmt.setString(1,showid);
                   
                    ResultSet rs = prepStmt.executeQuery();
                    
                    while(rs.next()){
                        if(rs.getString(1).equals(seatno)){
                             JFrame f = new JFrame();
                             JOptionPane.showMessageDialog(f,seatno+" Seat is unavailable! Already Booked");
                             f.setVisible(true);
                             flag=1;
                             break;
                        }
                    }
                    connect.close();
                }
                
                catch(Exception e){}
             
                if(flag==0){
                try{
                Class.forName("com.mysql.jdbc.Driver");  
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
                PreparedStatement stmt=con.prepareStatement("insert into seats values(?,?,?,?,?)");  
                stmt.setString(1,seatno);
                stmt.setString(2,bid);
                stmt.setString(3,showid);
                stmt.setString(4,"Booked");
                stmt.setString(5,"LastRow");
                
                int i2=stmt.executeUpdate();
            
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f,seatno+" Seat booked Successfully");
                f.setVisible(true);
            
                con.close();
       
        }
        
        catch(Exception e){
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f,"Insertion failed");
                f.setVisible(true);
        }
                }
            
            
            }
        }
        k++;
    }
        
    }//GEN-LAST:event_jTable6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int total=0;
        int count=0;
        int seatsfr=0,seatsmr=0,seatslr=0;
        try{
             Class.forName("com.mysql.jdbc.Driver");  
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
              String query = "select * from seats where BookingID=?";
              PreparedStatement prepStmt = con.prepareStatement(query);
              prepStmt.setString(1,bid);
                    
             ResultSet rs = prepStmt.executeQuery();
             
             while(rs.next()){
                 count++;
                 
                    try{
                        Class.forName("com.mysql.jdbc.Driver");  
                     Connection con2=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
                     String query2 = "select * from screen where ScreenID =?";
                    PreparedStatement prepStmt2 = con2.prepareStatement(query2);
                    prepStmt2.setString(1,screenid);
                   
                    ResultSet rs2 = prepStmt2.executeQuery();
                    int pricefr,pricemr,pricelr;
                    if(rs2.next()){
                    
                    pricefr = rs2.getInt(6);
                     pricemr = rs2.getInt(7);
                     pricelr = rs2.getInt(8);
                    
                 
                    
                    if(rs.getString(5).equals("FrontRow")){
                        total+=pricefr;
                        try{
                             Class.forName("com.mysql.jdbc.Driver");  
                            Connection con3=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
                            String query3 = "select * from shows where screenid =? and showid=?";
                            PreparedStatement prepStmt3 = con3.prepareStatement(query3);
                            prepStmt3.setString(1,screenid);
                            prepStmt3.setString(2,showid);
                   
                            ResultSet rs3 = prepStmt3.executeQuery();
                            
                            if(rs3.next())
                                seatsfr=rs3.getInt(6);
                            seatsfr--;
                            
                            con3.close();
                            
                        }
                        
                        catch(Exception e){}
                        
                        try{
                            Class.forName("com.mysql.jdbc.Driver");  
                            Connection con4=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
 

    
                            PreparedStatement stmt4 = con4.prepareStatement("update shows set capacityfr=? where showid=?"); 
                            stmt4.setInt(1,seatsfr);
                            stmt4.setString(2,showid);
                             stmt4.executeUpdate();
      
                         con4.close();
                         }
                        catch(Exception e){}
                        
                            
                        }
                    if(rs.getString(5).equals("MiddleRow")){
                        total+=pricemr;
                         try{
                             Class.forName("com.mysql.jdbc.Driver");  
                            Connection con5=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
                            String query5 = "select * from shows where screenid =? and showid=?";
                            PreparedStatement prepStmt5 = con5.prepareStatement(query5);
                            prepStmt5.setString(1,screenid);
                            prepStmt5.setString(2,showid);
                   
                            ResultSet rs5 = prepStmt5.executeQuery();
                            
                            if(rs5.next())
                                seatsmr=rs5.getInt(7);
                            seatsmr--;
                            
                            con5.close();
                            
                        }
                        
                        catch(Exception e){}
                        
                        try{
                            Class.forName("com.mysql.jdbc.Driver");  
                            Connection con6=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
 

    
                            PreparedStatement stmt6 = con6.prepareStatement("update shows set capacitymr=? where showid=?"); 
                            stmt6.setInt(1,seatsmr);
                            stmt6.setString(2,showid);
                             stmt6.executeUpdate();
      
                         con6.close();
                         }
                        catch(Exception e){}
                    }
                    
                    if(rs.getString(5).equals("LastRow")){
                        
                        total+=pricelr;
                         
                        try{
                             Class.forName("com.mysql.jdbc.Driver");  
                            Connection con7=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
                            String query7 = "select * from shows where screenid =? and showid=?";
                            PreparedStatement prepStmt7 = con7.prepareStatement(query7);
                            prepStmt7.setString(1,screenid);
                            prepStmt7.setString(2,showid);
                   
                            ResultSet rs7 = prepStmt7.executeQuery();
                            
                            if(rs7.next()){
                                seatslr=rs7.getInt(8);
                                seatslr--;
                                
                            }
                            
                            con7.close();
                            
                        }
                        
                        catch(Exception e){}
                        
                        try{
                            Class.forName("com.mysql.jdbc.Driver");  
                            Connection con8=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
                               
                            PreparedStatement stmt8 = con8.prepareStatement("update shows set capacitylr=? where showid=?"); 
                            stmt8.setInt(1,seatslr);
                            stmt8.setString(2,showid);
                             stmt8.executeUpdate();
      
                         con8.close();
                         }
                        catch(Exception e){}
                    
                    }
                    
                    }
                    con2.close();
                    }
                    
                    catch(Exception e){}
                 
                 }
                 
               
                con.close();
             }
             
   
        
        catch(Exception e){}
        
        
        try{
             Class.forName("com.mysql.jdbc.Driver");  
             Connection con3=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
             PreparedStatement stmt=con3.prepareStatement("insert into booking values(?,?,?,?,?)"); 
             stmt.setString(1,username);
             stmt.setString(2,bid);
             stmt.setString(3,showid);
             stmt.setInt(4,count);
             stmt.setInt(5,total);
             int i4=stmt.executeUpdate();
            
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f,"Booking done Successfully");
            f.setVisible(true);
            
            con3.close();
             
        }
        
        catch(Exception e){}
       
        
        BookingConfirmation m = new BookingConfirmation(username,bid);
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    // End of variables declaration//GEN-END:variables
}
