/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
//import net.proteanit.sql.DbUtils;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;

public class Theatredetails extends javax.swing.JFrame {

    /**
     * Creates new form Theatredetails
     */
    String username;
    public Theatredetails() {
        initComponents();
        Display();
    }
    
    public Theatredetails(String user){
        username=user;
        initComponents();
        setTitle("VIEW THEATRE DETAILS");
        Display();
    }
    private void Display(){
    
  //Theatreownerlogin t = new Theatreownerlogin();
  //String username = t.jTextField1.getText();
        try{
                    Class.forName("com.mysql.jdbc.Driver");  
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
                   String query = "select * from theatre where username = ?";
                    PreparedStatement prepStmt = con.prepareStatement(query);                   
                    prepStmt.setString(1,username); 
                    ResultSet rs = prepStmt.executeQuery();
                    
                 //   Statement stmt=con.createStatement();  
                 
                    //ResultSet rs=stmt.executeQuery("select * from theatre where username ");  
                    jTable2.setFont(new Font("Times New Roman", Font.BOLD, 18));
                    DefaultTableModel table1=(DefaultTableModel)jTable2.getModel();
                      
                    while(rs.next()){
                        String name = rs.getString(1);
                        String owner = rs.getString(2);
                        String address = rs.getString(3);
                        String city = rs.getString(4);
                        String screens= Integer.toString(rs.getInt(5));
                        String reg=rs.getString(6);
                        String arr[] ={name,owner,address,city,screens,reg};
                      //jtable1.setModel(DbUtils.resultSetToTableModel(rs));
                        table1.addRow(arr);
                     
                    }
              
                    
                    con.close();               
                   
        }
       
       catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Owner", "Address", "City", "No of screens", "Registration Number"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(300);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(31, 270, 1387, 87);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("ADD SCREEN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 441, 185, 37);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("VIEW SCREENS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(431, 441, 213, 37);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("BACK TO HOMEPAGE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(853, 557, 291, 37);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("DELETE THEATRE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(688, 441, 249, 37);

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setText("UPDATE THEATRE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(973, 441, 251, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\Saved Pictures\\cinema.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1450, 40, 1330, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        AddScreen s = new AddScreen(username);
        s.setVisible(true);
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        int selectedRow = jTable2.getSelectedRow();
       String regNo=model.getValueAt(selectedRow, 5).toString();
       s.jTextField2.setText(regNo);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        int selectedRow = jTable2.getSelectedRow();
       String regNo=model.getValueAt(selectedRow, 5).toString();
       ViewScreen s = new ViewScreen(regNo,username);
        s.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TheatreHomepage t = new TheatreHomepage(username);
        t.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        int selectedRow = jTable2.getSelectedRow();
      
       String regno=model.getValueAt(selectedRow,5).toString();
       
       Connection connection;
        try{
            Class.forName("com.mysql.jdbc.Driver");
  connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
  
   
    PreparedStatement st = connection.prepareStatement("DELETE FROM shows WHERE RegistrationNumber=?");
    
    st.setString(1,regno);
   // st.setString(2,username);
   
   
        st.executeUpdate(); 
        JFrame f = new JFrame();
        
        JOptionPane.showMessageDialog(f,"Deleted shows in the screens of the theatre successfully");
        
    } catch(Exception e) {
        JFrame f = new JFrame();
        
        JOptionPane.showMessageDialog(f,"Deletion failed");
    }
         try{
            Class.forName("com.mysql.jdbc.Driver");
  connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
  
   
    PreparedStatement st = connection.prepareStatement("DELETE FROM screen WHERE RegistrationNumber=?");
    
    st.setString(1,regno);
 //   st.setString(2,username);
   
   
        st.executeUpdate(); 
        JFrame f = new JFrame();
        
        JOptionPane.showMessageDialog(f,"Deleted screens in the theatre successfully");
        
    } catch(Exception e) {
        JFrame f = new JFrame();
        
        JOptionPane.showMessageDialog(f,"Deletion failed");
    }
         try{
            Class.forName("com.mysql.jdbc.Driver");
  connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
  
   
    PreparedStatement st = connection.prepareStatement("DELETE FROM theatre WHERE registrationno=? and username=?");
    
    st.setString(1,regno);
    st.setString(2,username);
   
   
        st.executeUpdate(); 
        JFrame f = new JFrame();
        
        JOptionPane.showMessageDialog(f,"Deleted theatre successfully");
        
    } catch(Exception e) {
        JFrame f = new JFrame();
        
        JOptionPane.showMessageDialog(f,"Deletion failed");
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        int selectedRow = jTable2.getSelectedRow();
      
       String regno=model.getValueAt(selectedRow,5).toString();
       UpdateTheatre t = new UpdateTheatre(username,regno);
       t.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Theatredetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Theatredetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Theatredetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Theatredetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Theatredetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
