
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class ViewShow extends javax.swing.JFrame {

    /**
     * Creates new form ViewShow
     */
    String RegNo,ScreenId;
    String username;
    public ViewShow() {
        initComponents();
    }
    public ViewShow(String regNo,String screenid,String user){
        RegNo=regNo;
        ScreenId=screenid;
        username=user;
        initComponents();
        setTitle("VIEW SHOW");
        Display();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void Display(){
    
  
        try{
          
                    Class.forName("com.mysql.jdbc.Driver");  
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
                    String query = "select * from shows where RegistrationNumber = ? and screenid = ?";
                    PreparedStatement prepStmt = con.prepareStatement(query);      
                    prepStmt.setString(1, RegNo);
                    prepStmt.setString(2,ScreenId);
                    ResultSet rs = prepStmt.executeQuery();
                    DefaultTableModel table1=(DefaultTableModel)jTable1.getModel();
                    while(rs.next()){
                        ScreenId = rs.getString(1);
                       String registrationNumber = rs.getString(2);
                       String movie = rs.getString(3);
                       String date = rs.getString(4);
                       String time = rs.getString(5);
                       String CapacityFR = Integer.toString(rs.getInt(6));
                        String CapacityMR = Integer.toString(rs.getInt(7));
                        String CapacityLR = Integer.toString(rs.getInt(8));
                        String showid=rs.getString(9);
                     
                        String arr[] ={ScreenId,registrationNumber,movie,date,time,CapacityFR,CapacityMR,CapacityLR,showid};
                        
                        table1.addRow(arr);
                         
                    }
                 //  jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                    
                    con.close();               
                   
        }
       
       catch(Exception e){}
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SCREENID", "REGISTRATION NUMBER", "MOVIE", "SHOW DATE", "SHOW TIME", "FRONT ROW SEATS", "MIDDLE ROW SEATS", "LAST ROW SEATS", "SHOW ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 275, 1276, 87);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("BACK TO HOMEPAGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(537, 553, 291, 37);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("DELETE SHOW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(282, 420, 209, 37);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("UPDATE SHOW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(552, 420, 209, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\Saved Pictures\\cinema.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1120, -30, 1520, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TheatreHomepage t = new TheatreHomepage(username);
        t.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow==-1){}
        else{
        String screenID=model.getValueAt(selectedRow, 0).toString();
        String showid=model.getValueAt(selectedRow,8).toString();
         Connection connection;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
  connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/movieticketbooking","root","");
  
    
    PreparedStatement st = connection.prepareStatement("DELETE FROM shows WHERE showid = ? and screenid=?");
    st.setString(1,showid);
    st.setString(2,screenID);
        st.executeUpdate(); 
        JFrame f = new JFrame();
        JOptionPane.showMessageDialog(f,"Deleted successfully");
        
    } catch(Exception e) {
        System.out.println(e);
    }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow==-1){}
        else{
        String screenID=model.getValueAt(selectedRow, 0).toString();
        String showid=model.getValueAt(selectedRow,8).toString();
        UpdateShow1 h = new UpdateShow1(showid,screenID,username);
        h.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewShow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
